### ISSUE TITLE
Documentación interactiva para la API

### ISSUE THREAD

**Issue by rparrapy** [reaccionpy/priorizador#2]
Integrar con [Flasgger](https://github.com/flasgger/flasgger) o similar para ofrecer documentación de la API.

**Comment by ivanarielcaceres** [comment]
Hola @rparrapy. Me he tomado la libertad de trabajar en esta Issue, ya que no tenía ningún asignado. He agregado la documentación de la API del endpoint get_json usando [Flasgger](https://github.com/flasgger/flasgger).
